Planning
Uni-Sopron/szta-23-kebeleicsaba pull request #2
Opened 2023-04-05 21:56 UTC by kebeleicsaba

2023-07-05 10:07 UTC, oliverosz requested changes

2023-07-05 10:07 UTC, oliverosz commented on docs/activity_chart/activity_chart.md
> +    GameLoop --> PlayerDecision{Player Decision}
A keverést meg laposztást minden fordulóban meg kell ismételni.

2023-07-05 10:07 UTC, oliverosz commented on docs/activity_chart/activity_chart.md
> +    CanPlayCard -- Yes --> HasColor{Has Card Of Chosen Color?}
Milyen "Chosen Color"? A színválasztás csak később szerepel a folyamatábrán.

2023-07-05 10:07 UTC, oliverosz commented on docs/activity_chart/activity_chart.md
> +    IsCardGreater -- No --> ChooseCard
Ebből szép kis végtelen ciklus lesz, ha egyik kártyája sem kijátszható a választott színből.

2023-07-05 10:07 UTC, oliverosz commented on docs/activity_chart/activity_chart.md
> +    DiscardCard --> DrawCard
Itt elég csak a kártyát kiválasztania, és nem kell semmilyen ellenőrzés, hiszen bármelyik kártya eldobható bármikor.

2023-07-05 10:07 UTC, oliverosz commented on docs/activity_chart/activity_chart.md
> +    CanDrawFromDiscard -- Yes --> DrawFromDiscard[Draw From Discard Pile]
Na de melyikből? Itt kell egy színválasztás és utána egy ellenőrzés, hogy az adott színből van-e kártya a discarban.

2023-07-05 10:07 UTC, oliverosz commented on docs/activity_chart/activity_chart.md
> +    Scoring --> End((End))
A pontozást minden forduló végén meg kell ejteni, mert ha visszakerülnek a lapok a pakliba, akkor már nem tudod kiszámolni a forduló pontszámait.

2023-07-05 10:07 UTC, oliverosz commented on docs/activity_chart/activity_chart.md
Valahogy annak is meg kéne jelennie a folyamatban, hogy felváltva kerülnek sorra a játékosok.

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +    Game --> "*" Player : has
Pontosan 2 játékos van, nem?

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +    Hand --> "*" Card : contains
A "has" meg a "contains" kapcsolatra megvannak a szabványos nyíltípusok: ![](https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Uml_classes_en.svg/300px-Uml_classes_en.svg.png)

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +    Player --> "*" Expedition : has
5 db, vagy 0..5, ha üresek tárolása helyett a lista méretét változtatod.

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +    }
Hogy fogsz tudni ide lapot eldobni?

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +    class Expedition{
Ez miért nem az AbstractPile leszármazottja?

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +      +shuffle()
Keverni csak a húzópaklit lehet, az nem közös.

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +      +selectCard(Card) : Card
Itt nem értem, hogy milyen kártyát kap paraméterben.

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +      #cards
Hiányzik a kapcsolat a Carddal.

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +      +highestValue() : int
A highestValue az ugyanaz lesz mint a topCard, úgyhogy felesleges rá külön metódus.

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +      #currentPlayer
Azt is tárolni kell, hogy hányadik fordulónál tart a játék.

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +      #expeditions
A pontszámot is el kell tárolni, mert a korábbi fordulók pontjait meg kell jegyezni.

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +      #cards
A cards tagot megörökli az AbstractPile-ból, bár igazából nem kéne abból származnia, mert itt a getTopCardnak nincs értelme.

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +      +calculateScores()
Ez nem fogja tudni kiszámolni a pontokat, mert a Player publikus interfésze erre nem nyújt lehetőséget.

2023-07-05 10:07 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +    }
Meg ha jól értem, a getTopCard az már el is távolítja a felső lapot (get helyett jobb lenne draw elnevezés), viszont akkor a discardPile felső lapját nem lehet lekérdezni, pedig azt meg kell tudni jeleníteni.

2023-07-05 19:12 UTC, oliverosz requested changes
Most már az attribútumok kb. jók az osztálydiagramon, csak a kapcsolatok jelölését kell javítani.

2023-07-05 19:12 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +    Hand <|-- AbstractPile
Hű, az AbstractPile öröklődik a Handből? Az nem jó.
Amúgy az absztrakt osztályt jelöld az `<<Abstract>>` annotációval.

2023-07-05 19:12 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +    AbstractPile o-- "*" Card : contains
Ez inkább kompozíció, mert a pile az kártyákból áll. A "has" relációk az aggregációk, azokat a nyilakat is cseréld le.

2023-07-05 19:12 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
>        +turn(Player, dict)
Mik ezek a dictek?

2023-07-05 19:12 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
>        +playCard(Card, str)
És itt az str?

2023-07-05 19:12 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +      +containsWager() : bool
Igazából a megjelenítéshez az összes benne lévő lap kell, és akkor ez feleslegessé válik.

2023-07-05 19:16 UTC, kebeleicsaba commented on docs/class_diagram/class_diagram.md
>        +turn(Player, dict)
Itt arra gondoltam, hogy egy result dict-et ad vissza az end és azt tudja majd használni a view. A turnnél meg egy action `{"type": "play" or "discard", "card": card, "location": color, "draw_from": "deck" or color}`

2023-07-05 19:23 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
>        +turn(Player, dict)
Hmm, akkor csak a kör végén frissíted a modellt? Jobb lenne minden egyes döntésnél. A View-nak meg szerintem kelleni fog egy getPlayer(int), meg getDiscardPiles(), stb. De ha ezek a kezdeti tervekben nincsenek, az nem nagy gond.

2023-07-05 19:46 UTC, oliverosz requested changes

2023-07-05 19:46 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +      +playCard(Card, Expedition)
Az Expedition nem kell, a Card színe meghatározza, hova kell kijátszani.

2023-07-05 19:46 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +    Expedition --* "*" Card : contains
Ez itt fordítva van.
A has/contains címkék meg nem kellenek, pont ezt jelölik a nyílhegyek. Olyankor kell címke, ha valamiből mondjuk több van, de más role-ban. Például ha a currentPlayer egy Player referencia lenne, akkor a Game és a Player közt lenne egy aggregáció meg egy asszociáció kapcsolat is, akkor fel kéne címkézni hogy melyik melyik.
De nálad gondolom a currentPlayer egy index. Mondjuk jó lenne jelölni a tagváltozók típusait is.

2023-07-05 19:46 UTC, oliverosz commented on docs/class_diagram/class_diagram.md
> +      +getAllCards() : List[Card]
a `list` kisbetűs

2023-07-06 20:20 UTC, oliverosz commented on docs/activity_chart/activity_chart.md
> +    Scoring --> End((End))
A forduló végén, nem a játékos körének a végén.

2023-07-06 20:21 UTC, oliverosz commented on docs/activity_chart/activity_chart.md
> +    PlayerDecision -->|Play a Card| HasPlayableCard{Has Playable Card Of Any Color?}
Mondjuk akkor logikusabb lenne ezt a döntése előtt leellenőrizni.

2023-07-06 20:22 UTC, oliverosz commented on docs/activity_chart/activity_chart.md
> +    PlayerSwitch --> GameLoop[Game Loop Start]
Kicsit fura, hogy játékosváltással kezdődik a játék.

2023-07-06 21:46 UTC, oliverosz approved these changes

2023-07-06 21:51 UTC, merged